export const INIT_BREAKING_BAD = 'INIT_BREAKING_BAD';

export const PROCESSING_BREAKING_BAD = 'PROCESSING_BREAKING_BAD';

export const BREAKING_BAD_SUCCESS = 'BREAKING_BAD_SUCCESS';

export const SEARCH_CHARACTER_SUCCESS = 'SEARCH_CHARACTER_SUCCESS';

export const SEARCH_CHARACTER_REQUEST = 'SEARCH_CHARACTER_REQUEST';

export const SEARCH_CHARACTER_FAILED = 'SEARCH_CHARACTER_FAILED';


export const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA';

export const BREAKING_BAD_FAILURE = 'BREAKING_BAD_FAILURE';

export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';

export const REMOVE_FAVOURITES = 'REMOVE_FAVOURITES';